services:
  - type: web
    name: eventflow-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: eventflow-db
          property: connectionString
      - key: CLIENT_URL
        value: https://event-flow.netlify.app/
      - key: JWT_SECRET
        value: TXvRbyL1svtygGm786syal4DkvvDrBPLp/ge/goG/SA=
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: STRIPE_SECRET_KEY
        value: sk_test_51UHIrhJNNJYXercBCjw771mjsWgeIDTYh7FsRcLo4A4y6ZUEW2cyW5O3IqyZ9EkOP02dEUpJ3hS9gpVcsYez5jiQ00GNqHCxqO
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_311fa22963477e66ed0dcd018da4df0a0486da0c32683cca55cfaf84aa897895
      - key: PASSWORD_RESET_URL
        value: https://event-flow.netlify.app/reset-password
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 1000
      - key: SMTP_HOST
        value: smtp.example.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_FROM
        value: EventFlow <no-reply@example.com>

databases:
  - name: eventflow-db
    plan: free
    databaseName: eventflow
